[package]
name = "HelloNFT"
version = "1.0.0"
authors = []

[addresses]
initial_creator_addr = "_"
property_test = "_"
admin_addr = "_"
econia =   "0xc0de11113b427d35ece1d8991865a941c0578b0f349acabbe9753863c24109ff"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-framework" }
AptosTokenObjects = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-token-objects" }
Econia = { git = "https://github.com/econia-labs/econia.git", rev = "testnet", subdir = "src/move/econia" }

[dev-dependencies]
