[package]
name = "HelloNFT"
version = "1.0.0"
authors = []

[addresses]
message_board_addr = "_"
launchpad_addr = "_"
initial_creator_addr = "_"
property_test = "_"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-framework" }
AptosTokenObjects = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-token-objects" }

[dev-dependencies]
